name: jobfaster_application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  firebase_core: ^2.12.0
  flutter_downloader: ^1.6.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  file_picker: ^4.0.0
  dio: ^5.1.2
  get_it: ^7.2.0
  intl: ^0.17.0
  http: ^0.13.3
  permission_handler_platform_interface: ^3.0.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
